### ISSUE TITLE
Page Access Token vs VERIFY_TOKEN & linking pages in FB app setup.

### ISSUE THREAD

**Issue by aspiringguru** [waleedahmad/Aww-Bot#1]
Just checking I'm reading the setup notes as intended.

within the facebook app setup there is requirement to nominate
Page Access Token & select a page to link token generation to.

when setting up webhooks, there is requirement to nominate the callback url,  verify token and 
"Select a page to subscribe your webhook to the page events"

within the code, we have VERIFY_TOKEN (matches the webhooks verify token immediately above).

but the writeup does not mention the page access token, or selecting the FB page in two places within the facebook app config.  Not sure if FB has changed this since article was written in June 2018.

**Comment by waleedahmad** [comment]
It's [mentioned](https://quantizd.com/building-facebook-messenger-bot-with-nodejs/#more-771) at the start under Getting Started heading.
